apiVersion: v1
kind: Namespace
metadata:
  name: flipper-operator-system
  labels:
    app.kubernetes.io/name: flipper-operator

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipper-operator-controller-manager
  namespace: flipper-operator-system
  labels:
    app.kubernetes.io/name: flipper-operator
    control-plane: controller-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - name: manager
        image: pai314/flipper-operator:latest
        imagePullPolicy: Always
        command:
        - /manager
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "10m"
            memory: "64Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
      serviceAccountName: flipper-operator-controller-manager
      terminationGracePeriodSeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
